name: Build Clash YAML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install subconverter
        run: |
          git clone https://github.com/tindy2013/subconverter.git

      - name: Start subconverter
        run: |
          cd subconverter
          chmod +x subconverter
          nohup ./subconverter > /dev/null 2>&1 &
          sleep 10

      - name: Generate YAML
        run: |
          mkdir -p docs

          curl -o docs/HMQ.yaml \
          "http://127.0.0.1:25500/sub?target=clash&url=https://raw.githubusercontent.com/JettKing/Nodal/main/HMQ"

      - name: Push YAML
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add .
          git commit -m "auto build yaml" || echo done
          git push
