name: Generate Clash Meta YAML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Subconverter
        run: |

          docker run -d \
          --name subconverter \
          -p 25500:25500 \
          tindy2013/subconverter

          sleep 15

      - name: Generate YAML
        run: |

          mkdir -p docs

          files=("vpn" "HMQ" "FYH" "HYL" "LXS" "WXQ" "WXY")

          for file in "${files[@]}"
          do

            curl -L -o docs/${file}.yaml \
            "http://127.0.0.1:25500/sub?target=clashmeta&url=https://raw.githubusercontent.com/${{ github.repository }}/main/${file}&insert=false&emoji=true&list=false"

          done

      - name: Deploy
        run: |

          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          git add docs/*.yaml
          git commit -m "update yaml" || echo "no changes"

          git push