name: Build Clash YAML

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download subconverter
        run: |

          wget https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz

          tar -zxvf subconverter_linux64.tar.gz

          chmod +x subconverter/subconverter

      - name: Start subconverter
        run: |

          cd subconverter

          nohup ./subconverter > /dev/null 2>&1 &

          sleep 10

      - name: Generate YAML
        run: |

          mkdir -p docs

          files=("vpn" "FYH" "HMQ" "HYL" "LXS" "WXQ" "WXY")

          for file in "${files[@]}"
          do

            echo "Generating ${file}.yaml"

            curl -L -o docs/${file}.yaml \
            "http://127.0.0.1:25500/sub?target=clash&url=https://raw.githubusercontent.com/JettKing/Nodal/main/${file}"

          done

      - name: Push YAML
        run: |

          git config --global user.name github-actions

          git config --global user.email github-actions@github.com

          git add docs/*.yaml

          git commit -m "auto build yaml" || echo "no changes"

          git push
